package bo.edu.cba;

import java.util.ArrayList;
import java.util.List;

public class VerbsList {
    public static List<Verb> getVerbsList() {
        List<Verb> miListaDeObjetos = new ArrayList<>();

        miListaDeObjetos.add(new Verb(1, "Be", "Was/Were", "Been", "Ser / Estar", "She is a teacher.", "They were very happy yesterday.", "I have been to London.", "Ella es profesora.", "Estaban muy contentos ayer.", "He estado en Londres."));
        miListaDeObjetos.add(new Verb(2, "Beat", "Beat", "Beaten", "Golpear / Ganar", "Our team always beats them.", "He beat me at chess yesterday.", "Our team has never been beaten.", "Nuestro equipo siempre les gana.", "Él me ganó ayer al ajedrez.", "Nuestro equipo nunca ha sido vencido."));
        miListaDeObjetos.add(new Verb(3, "Become", "Became", "Become", "Convertirse en / Llegar a ser", "He wants to become a doctor.", "She became famous overnight.", "He has become a great leader.", "Él quiere convertirse en médico.", "Ella se hizo famosa de la noche a la mañana.", "Él se ha convertido en un gran líder."));
        miListaDeObjetos.add(new Verb(4, "Begin", "Began", "Begun", "Empezar", "The class begins at 9 AM.", "He began to feel ill.", "The show has already begun.", "La clase empieza a las 9 AM.", "Él empezó a sentirse mal.", "El espectáculo ya ha comenzado."));
        miListaDeObjetos.add(new Verb(5, "Bend", "Bent", "Bent", "Doblar / Inclinarse", "Don't bend the rules.", "He bent down to tie his shoe.", "The branch was bent by the wind.", "No infrinjas las reglas.", "Se agachó para atarse el zapato.", "La rama fue doblada por el viento."));
        miListaDeObjetos.add(new Verb(6, "Bet", "Bet", "Bet", "Apostar", "I bet you can't do it.", "He bet all his money on that horse.", "I have bet on the winning team.", "Apuesto a que no puedes hacerlo.", "Apostó todo su dinero en ese caballo.", "He apostado por el equipo ganador."));
        miListaDeObjetos.add(new Verb(7, "Bite", "Bit", "Bitten", "Morder", "Does your dog bite?", "The snake bit him on the leg.", "She has been bitten by a mosquito.", "¿Tu perro muerde?", "La serpiente lo mordió en la pierna.", "Ha sido picada por un mosquito."));
        miListaDeObjetos.add(new Verb(8, "Blow", "Blew", "Blown", "Soplar", "The wind blows gently here.", "She blew out the candles.", "The storm has blown the roof off.", "El viento sopla suavemente aquí.", "Ella sopló las velas.", "La tormenta ha arrancado el tejado."));
        miListaDeObjetos.add(new Verb(9, "Break", "Broke", "Broken", "Romper", "Be careful not to break the glass.", "He broke his leg playing football.", "My phone screen is broken.", "Ten cuidado de no romper el vaso.", "Se rompió la pierna jugando al fútbol.", "La pantalla de mi teléfono está rota."));
        miListaDeObjetos.add(new Verb(10, "Bring", "Brought", "Brought", "Traer", "Can you bring me a glass of water?", "She brought a cake to the party.", "Have you brought your homework?", "¿Puedes traerme un vaso de agua?", "Ella trajo un pastel a la fiesta.", "¿Has traído tus deberes?"));
        miListaDeObjetos.add(new Verb(11, "Build", "Built", "Built", "Construir", "They plan to build a new bridge.", "He built this house himself.", "The castle was built in the 15th century.", "Planean construir un nuevo puente.", "Él construyó esta casa por sí mismo.", "El castillo fue construido en el siglo XV."));
        miListaDeObjetos.add(new Verb(12, "Buy", "Bought", "Bought", "Comprar", "I need to buy some milk.", "She bought a new car last week.", "I have bought a gift for you.", "Necesito comprar algo de leche.", "Compró un coche nuevo la semana pasada.", "He comprado un regalo para ti."));
        miListaDeObjetos.add(new Verb(13, "Catch", "Caught", "Caught", "Atrapar", "Let's play catch.", "The police caught the thief.", "He has caught a cold.", "Juguemos a atrapar la pelota.", "La policía atrapó al ladrón.", "Se ha resfriado."));
        miListaDeObjetos.add(new Verb(14, "Choose", "Chose", "Chosen", "Elegir", "You must choose a path.", "She chose the blue dress.", "He has been chosen as team captain.", "Debes elegir un camino.", "Ella eligió el vestido azul.", "Ha sido elegido capitán del equipo."));
        miListaDeObjetos.add(new Verb(15, "Come", "Came", "Come", "Venir", "Please come to my party.", "He came home late last night.", "Has the mail come yet?", "Por favor, ven a mi fiesta.", "Llegó tarde a casa anoche.", "¿Ha llegado ya el correo?"));
        miListaDeObjetos.add(new Verb(16, "Cost", "Cost", "Cost", "Costar", "How much does it cost?", "This book cost me $20.", "The repairs have cost more than we expected.", "¿Cuánto cuesta?", "Este libro me costó 20 dólares.", "Las reparaciones han costado más de lo que esperábamos."));
        miListaDeObjetos.add(new Verb(17, "Cut", "Cut", "Cut", "Cortar", "Cut the cake into six pieces.", "I cut my finger while cooking.", "She has cut her hair short.", "Corta el pastel en seis trozos.", "Me corté el dedo mientras cocinaba.", "Se ha cortado el pelo."));
        miListaDeObjetos.add(new Verb(18, "Deal", "Dealt", "Dealt", "Tratar / Lidiar", "It's your turn to deal the cards.", "She dealt with the problem effectively.", "We have dealt with this company before.", "Es tu turno de repartir las cartas.", "Ella manejó el problema eficazmente.", "Ya hemos tratado con esta empresa antes."));
        miListaDeObjetos.add(new Verb(19, "Dig", "Dug", "Dug", "Cavar", "The dog likes to dig holes.", "They dug for treasure on the island.", "A deep well was dug here.", "Al perro le gusta cavar hoyos.", "Cavaron en busca de tesoros en la isla.", "Aquí se cavó un pozo profundo."));
        miListaDeObjetos.add(new Verb(20, "Do", "Did", "Done", "Hacer", "You can do it!", "I did my homework.", "Have you done the dishes?", "¡Puedes hacerlo!", "Hice mis deberes.", "¿Has lavado los platos?"));
        miListaDeObjetos.add(new Verb(21, "Draw", "Drew", "Drawn", "Dibujar / Sacar", "Can you draw a map for me?", "She drew a beautiful picture.", "The curtains were drawn.", "¿Puedes dibujarme un mapa?", "Ella dibujó un cuadro precioso.", "Las cortinas estaban corridas."));
        miListaDeObjetos.add(new Verb(22, "Drink", "Drank", "Drunk", "Beber", "Remember to drink water.", "He drank a whole bottle of soda.", "I have drunk too much coffee today.", "Recuerda beber agua.", "Se bebió una botella entera de refresco.", "He bebido demasiado café hoy."));
        miListaDeObjetos.add(new Verb(23, "Drive", "Drove", "Driven", "Conducir", "I am learning to drive.", "She drove me to the airport.", "Have you ever driven a truck?", "Estoy aprendiendo a conducir.", "Ella me llevó al aeropuerto.", "¿Alguna vez has conducido un camión?"));
        miListaDeObjetos.add(new Verb(24, "Eat", "Ate", "Eaten", "Comer", "What do you want to eat?", "We ate pizza last night.", "I haven't eaten breakfast yet.", "¿Qué quieres comer?", "Anoche comimos pizza.", "Todavía no he desayunado."));
        miListaDeObjetos.add(new Verb(25, "Fall", "Fell", "Fallen", "Caer", "Leaves fall in autumn.", "He fell off his bike.", "The temperature has fallen sharply.", "Las hojas caen en otoño.", "Se cayó de su bicicleta.", "La temperatura ha caído bruscamente."));
        miListaDeObjetos.add(new Verb(26, "Feed", "Fed", "Fed", "Alimentar", "It's time to feed the cat.", "I fed the baby an hour ago.", "The animals have already been fed.", "Es hora de alimentar al gato.", "Alimenté al bebé hace una hora.", "Los animales ya han sido alimentados."));
        miListaDeObjetos.add(new Verb(27, "Feel", "Felt", "Felt", "Sentir", "I feel happy today.", "She felt a sharp pain in her back.", "He has never felt so alive.", "Hoy me siento feliz.", "Sintió un dolor agudo en la espalda.", "Nunca se ha sentido tan vivo."));
        miListaDeObjetos.add(new Verb(28, "Fight", "Fought", "Fought", "Pelear / Luchar", "They fight for their rights.", "The soldiers fought bravely.", "She has fought against injustice all her life.", "Luchan por sus derechos.", "Los soldados lucharon con valentía.", "Ha luchado contra la injusticia toda su vida."));
        miListaDeObjetos.add(new Verb(29, "Find", "Found", "Found", "Encontrar", "I can't find my keys.", "She found a wallet on the street.", "Have you found a solution?", "No encuentro mis llaves.", "Encontró una cartera en la calle.", "¿Has encontrado una solución?"));
        miListaDeObjetos.add(new Verb(30, "Fit", "Fit", "Fit", "Encajar / Quedar bien", "These shoes don't fit me.", "The tailor fitted him for a new suit.", "The new part has been fitted.", "Estos zapatos no me quedan bien.", "El sastre le probó un traje nuevo.", "La nueva pieza ha sido instalada."));
        miListaDeObjetos.add(new Verb(31, "Fly", "Flew", "Flown", "Volar", "Birds can fly.", "We flew from New York to Paris.", "I have never flown in a helicopter.", "Los pájaros pueden volar.", "Volamos de Nueva York a París.", "Nunca he volado en helicóptero."));
        miListaDeObjetos.add(new Verb(32, "Forget", "Forgot", "Forgotten", "Olvidar", "Don't forget to call me.", "I forgot his name.", "The old traditions are almost forgotten.", "No te olvides de llamarme.", "Olvidé su nombre.", "Las viejas tradiciones están casi olvidadas."));
        miListaDeObjetos.add(new Verb(33, "Forgive", "Forgave", "Forgiven", "Perdonar", "It's important to forgive others.", "She forgave him for what he did.", "He has not been forgiven.", "Es importante perdonar a los demás.", "Ella le perdonó por lo que hizo.", "No ha sido perdonado."));
        miListaDeObjetos.add(new Verb(34, "Freeze", "Froze", "Frozen", "Congelar", "Water freezes at 0°C.", "I froze when I saw the spider.", "The lake is frozen solid.", "El agua se congela a 0°C.", "Me quedé helado cuando vi la araña.", "El lago está completamente congelado."));
        miListaDeObjetos.add(new Verb(35, "Get", "Got", "Got/Gotten", "Obtener / Conseguir", "You can get a discount.", "I got a new job last month.", "She has gotten much better.", "Puedes conseguir un descuento.", "Conseguí un nuevo trabajo el mes pasado.", "Ella ha mejorado mucho."));
        miListaDeObjetos.add(new Verb(36, "Give", "Gave", "Given", "Dar", "Can you give me a hand?", "He gave her a beautiful gift.", "I have given it a lot of thought.", "¿Puedes echarme una mano?", "Él le dio un hermoso regalo.", "Lo he pensado mucho."));
        miListaDeObjetos.add(new Verb(37, "Go", "Went", "Gone", "Ir", "We need to go now.", "They went to the beach yesterday.", "She has gone to the store.", "Tenemos que irnos ahora.", "Fueron a la playa ayer.", "Ella ha ido a la tienda."));
        miListaDeObjetos.add(new Verb(38, "Grow", "Grew", "Grown", "Crecer / Cultivar", "Children grow up so fast.", "He grew tomatoes in his garden.", "My plant has grown a lot.", "Los niños crecen muy rápido.", "Cultivó tomates en su jardín.", "Mi planta ha crecido mucho."));
        miListaDeObjetos.add(new Verb(39, "Hang", "Hung", "Hung", "Colgar", "Hang your coat over there.", "She hung the picture on the wall.", "The clothes have been hung out to dry.", "Cuelga tu abrigo allí.", "Colgó el cuadro en la pared.", "La ropa ha sido tendida para secar."));
        miListaDeObjetos.add(new Verb(40, "Have", "Had", "Had", "Tener", "I have a question.", "We had a great time.", "I've had enough.", "Tengo una pregunta.", "Lo pasamos muy bien.", "He tenido suficiente."));
        miListaDeObjetos.add(new Verb(41, "Hear", "Heard", "Heard", "Oír", "Can you hear that noise?", "I heard the news on the radio.", "Have you heard about the new plan?", "¿Puedes oír ese ruido?", "Escuché la noticia en la radio.", "¿Has oído hablar del nuevo plan?"));
        miListaDeObjetos.add(new Verb(42, "Hide", "Hid", "Hidden", "Esconder", "Let's hide behind the tree.", "The cat hid under the bed.", "The treasure was hidden on the island.", "Escondámonos detrás del árbol.", "El gato se escondió debajo de la cama.", "El tesoro estaba escondido en la isla."));
        miListaDeObjetos.add(new Verb(43, "Hit", "Hit", "Hit", "Golpear", "Don't hit your brother.", "The ball hit the window.", "The town was hit by a storm.", "No golpees a tu hermano.", "La pelota golpeó la ventana.", "La ciudad fue azotada por una tormenta."));
        miListaDeObjetos.add(new Verb(44, "Hold", "Held", "Held", "Sostener / Mantener", "Please hold the door open.", "She held the baby in her arms.", "The meeting will be held tomorrow.", "Por favor, mantén la puerta abierta.", "Sostuvo al bebé en sus brazos.", "La reunión se celebrará mañana."));
        miListaDeObjetos.add(new Verb(45, "Hurt", "Hurt", "Hurt", "Herir / Doler", "Be careful not to hurt yourself.", "He hurt his knee playing soccer.", "My feelings have been hurt.", "Ten cuidado de no hacerte daño.", "Se lastimó la rodilla jugando al fútbol.", "Mis sentimientos han sido heridos."));
        miListaDeObjetos.add(new Verb(46, "Keep", "Kept", "Kept", "Mantener / Guardar", "You can keep the change.", "He kept his promise.", "The secret has been kept for years.", "Puedes quedarte con el cambio.", "Él mantuvo su promesa.", "El secreto se ha guardado durante años."));
        miListaDeObjetos.add(new Verb(47, "Know", "Knew", "Known", "Saber / Conocer", "I know the answer.", "I knew you would succeed.", "He is known for his honesty.", "Sé la respuesta.", "Sabía que tendrías éxito.", "Es conocido por su honestidad."));
        miListaDeObjetos.add(new Verb(48, "Lay", "Laid", "Laid", "Poner / Colocar", "The hen will lay an egg.", "She laid the table for dinner.", "The foundations have been laid.", "La gallina pondrá un huevo.", "Puso la mesa para la cena.", "Se han sentado las bases."));
        miListaDeObjetos.add(new Verb(49, "Lead", "Led", "Led", "Liderar / Guiar", "A good captain must lead.", "She led the team to victory.", "This path has led us to the lake.", "Un buen capitán debe liderar.", "Ella llevó al equipo a la victoria.", "Este camino nos ha llevado al lago."));
        miListaDeObjetos.add(new Verb(50, "Leave", "Left", "Left", "Dejar / Marcharse", "We have to leave now.", "He left his keys on the table.", "Has she left for work yet?", "Tenemos que irnos ahora.", "Dejó sus llaves sobre la mesa.", "¿Ya se ha ido a trabajar?"));
        miListaDeObjetos.add(new Verb(51, "Lend", "Lent", "Lent", "Prestar", "Could you lend me a pen?", "I lent my book to a friend.", "The bank has lent them the money.", "¿Podrías prestarme un bolígrafo?", "Le presté mi libro a un amigo.", "El banco les ha prestado el dinero."));
        miListaDeObjetos.add(new Verb(52, "Let", "Let", "Let", "Permitir / Dejar", "Let me help you.", "My parents let me go to the party.", "She has been let go from her job.", "Déjame ayudarte.", "Mis padres me dejaron ir a la fiesta.", "Ha sido despedida de su trabajo."));
        miListaDeObjetos.add(new Verb(53, "Lie", "Lied", "Lied", "Mentir", "He lies about his age.", "She lied to her parents.", "They have never lied to me.", "Él miente sobre su edad.", "Ella les mintió a sus padres.", "Nunca me han mentido."));
        miListaDeObjetos.add(new Verb(54, "Light", "Lit", "Lit", "Encender / Iluminar", "Can you light the candle?", "He lit the fire with one match.", "The room was lit by a single lamp.", "¿Puedes encender la vela?", "Encendió el fuego con una cerilla.", "La habitación estaba iluminada por una sola lámpara."));
        miListaDeObjetos.add(new Verb(55, "Lose", "Lost", "Lost", "Perder", "Don't lose your ticket.", "I lost my phone yesterday.", "The team has never lost a game.", "No pierdas tu billete.", "Perdí mi teléfono ayer.", "El equipo nunca ha perdido un partido."));
        miListaDeObjetos.add(new Verb(56, "Make", "Made", "Made", "Hacer / Fabricar", "Let's make a cake.", "She made a promise to me.", "This table is made of wood.", "Hagamos un pastel.", "Ella me hizo una promesa.", "Esta mesa está hecha de madera."));
        miListaDeObjetos.add(new Verb(57, "Mean", "Meant", "Meant", "Significar / Querer decir", "What does this word mean?", "I'm sorry, I meant to call you.", "This gift was meant for you.", "¿Qué significa esta palabra?", "Lo siento, quería llamarte.", "Este regalo era para ti."));
        miListaDeObjetos.add(new Verb(58, "Meet", "Met", "Met", "Conocer / Encontrarse", "Nice to meet you.", "We met at a conference.", "Have you met my brother?", "Encantado de conocerte.", "Nos conocimos en una conferencia.", "¿Conoces a mi hermano?"));
        miListaDeObjetos.add(new Verb(59, "Pay", "Paid", "Paid", "Pagar", "I need to pay the bills.", "He paid for dinner last night.", "Have you paid the electricity bill?", "Necesito pagar las facturas.", "Anoche pagó la cena.", "¿Has pagado la factura de la luz?"));
        miListaDeObjetos.add(new Verb(60, "Put", "Put", "Put", "Poner", "Put the book on the shelf.", "She put sugar in her coffee.", "I have put the keys on the table.", "Pon el libro en la estantería.", "Puso azúcar en su café.", "He puesto las llaves en la mesa."));

        return miListaDeObjetos;
    }
}
